version: '3.5'
services:
    local-laravel:
        container_name: 'local-laravel'
        build:
            context: ./docker/
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - 'local_backend'
        volumes:
            - ./:/var/www/html
        depends_on:
        - local-db

    local-db:
        image: mariadb:10.6
        container_name: "local-db"
        command:
            --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        networks:
            - 'local_backend'
        volumes:
            - maria_db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}

networks:
  local_backend:
        name: 'local_backend'

volumes:
    maria_db_data:
        name: 'test_maria_db_data'
